veridian/armorer/urls.py
from django.urls import path
from . import views

app_name = 'armorer'

urlpatterns = [
    path('armorer/', views.armorer, name='armorer'),
]

veridian/cities/urls.py
from django.urls import path
from . import views

app_name = 'cities'

urlpatterns = [
    path('cities/', views.cities, name='cities'),
]

veridian/home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home')
]

veridian/jeweler/urls.py
from django.urls import path
from . import views

app_name = 'jeweler'

urlpatterns = [
    path('jeweler/', views.jeweler, name='jeweler'),
]

veridian/tavern/urls.py
from django.urls import path
from . import views

app_name = 'tavern'
urlpatterns = [
    path('task_master/', views.task_master, name='task_master'),
    path('activate_task/<int:task_id>/', views.activate_task, name='activate_task'),
    path('complete_task/<int:task_id>/', views.complete_task, name='complete_task'),
    path('claim_reward/<int:task_id>/', views.claim_reward, name='claim_reward'),
    path('reset_tasks/', views.reset_tasks, name='reset_tasks'),  # Nowa ścieżka
]

veridian/veridian/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('team/', include('team.urls')),
    path('users/', include('users.urls')),
    path('world/', include('world.urls')),
    path('bots_farm/', include('bots_farm.urls')),
    path('fight', include('fight.urls')),
    path('items', include('items.urls')),
    path('inventory', include('inventory.urls')),
    path('cities/', include('cities.urls')),
    path('blacksmith/', include('blacksmith.urls')),
    path('arena/', include('arena.urls')),
    path('tavern/', include('tavern.urls')),
    path('jeweler/', include('jeweler.urls')),
    path('carpentry_shop/', include('carpentry_shop.urls')),
    path('clothier/', include('clothier.urls')),
    path('armorer/', include('armorer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

veridian/world/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "world"
urlpatterns = [
    path('main/', views.main , name='main')
]

veridian/cities/models.py
from django.db import models

# Create your models here.

veridian/cities/views.py
from django.shortcuts import render

def cities(request):
    return render(request, 'cities/cities.html')

veridian/cities/templates/cities/cities.html
{% extends "home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/City.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="container-md-6 mx-auto text-center ">
            <h2 style="background-color: DarkGray; color: black; font-weight: bold;">Welcome to the City</h2>
            <ul class="list-group">
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'armorer:armorer' %}">Visit the Armorer</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'blacksmith:blacksmith' %}">Visit the Blacksmith</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'carpentry_shop:carpentry_shop' %}">Visit the Carpentry Shop</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'clothier:clothier' %}">Visit the Clothier</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'jeweler:jeweler' %}">Visit the Jeweler</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'tavern:task_master' %}">Tavern</a>
                </li>
            </ul>
            <p><a class="btn btn-primary border border-secondary mt-3" href="{% url 'world:main' %}" style="background-color: DarkGray; color: black; font-weight: bold;">Go back to World</a></p>
        </div>
    </body>
{% endblock content %}