veridian/cities/urls.py
from django.urls import path
from . import views

app_name = 'cities'

urlpatterns = [
    path('cities/', views.cities, name='cities'),
]

veridian/fight/urls.py
from django.urls import path
from . import views

app_name = 'fight'
urlpatterns = [
    path('battle/', views.battle, name='battle'),
    path('countdown/', views.countdown, name='countdown'),
    path('fight_selector/', views.fight_selector, name='fight_selector'),
]

veridian/home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home')
]

veridian/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('equipment/', views.inventory, name='equipment'),
]

veridian/team/urls.py
from django.urls import path
from . import views

app_name = 'team'
urlpatterns = [
    path('create_character/', views.create_character, name='create_character'),
    path('character_list/', views.character_list, name='character_list'),
]

veridian/veridian/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('team/', include('team.urls')),
    path('users/', include('users.urls')),
    path('world/', include('world.urls')),
    path('bots_farm/', include('bots_farm.urls')),
    path('fight', include('fight.urls')),
    path('items', include('items.urls')),
    path('inventory', include('inventory.urls')),
    path('cities/', include('cities.urls')),
    path('blacksmith/', include('blacksmith.urls')),
    path('arena/', include('arena.urls')),
    path('tavern/', include('tavern.urls')),
    path('jeweler/', include('jeweler.urls')),
    path('carpentry_shop/', include('carpentry_shop.urls')),
    path('clothier/', include('clothier.urls')),
    path('armorer/', include('armorer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

veridian/world/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "world"
urlpatterns = [
    path('main/', views.main , name='main')
]

veridian/world/models.py
from django.db import models

# Create your models here.

veridian/world/views.py
from django.shortcuts import render
from team.models import Character

def main(request):
    user_character = Character.objects.filter(user=request.user).first()
    user_character_exists = user_character is not None
    return render(request, 'world/main.html', {'user_character_exists': user_character_exists})

veridian/world/templates/world/main.html
{% extends "home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/Background.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="container-md-6 mx-auto text-center">
            <h2 style="background-color: DarkGray; color: black; font-weight: bold;">Welcome to the World</h2>
            <ul class="list-group">
                {% if user_character_exists %}
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'cities:cities' %}">City</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'fight:fight_selector' %}">Fight</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'inventory:equipment'%}">Inventory</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a class="nav-link" href="{% url 'team:character_list' %}">Team</a>
                    </li>


                {% else %}
                    <div style="background-color: DarkGray; color: black; font-weight: bold;">
                        <p>You must create a character to access this content.</p>
                    </div>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'team:create_character' %}" class="btn btn-primary">Create Character</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </body>
{% endblock content %}